export const dropOffsetX = 4;
export const dropOffsetY = -1;
export const cellSize = 30;
export const currentPieceCanvasSize = 4;
export const fieldHeight = 20;
export const fieldWidth = 10;
export const stepSize = 1;
export const lineClearMultipliers = [0, 100, 300, 500, 800];
export const initialDropDelay = 1000;